# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
